#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("aTello.Resource", IsApplication=true)]

namespace aTello
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int barrierAllowsGoneWidgets = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int barrierDirection = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int chainUseRtl = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int constraintSet = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int constraint_referenced_ids = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int content = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int emptyVisibility = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int layout_constrainedHeight = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int layout_constrainedWidth = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int layout_constraintBaseline_creator = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int layout_constraintBaseline_toBaselineOf = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int layout_constraintBottom_creator = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int layout_constraintBottom_toBottomOf = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int layout_constraintBottom_toTopOf = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int layout_constraintCircle = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int layout_constraintCircleAngle = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int layout_constraintCircleRadius = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int layout_constraintDimensionRatio = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int layout_constraintEnd_toEndOf = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int layout_constraintEnd_toStartOf = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int layout_constraintGuide_begin = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int layout_constraintGuide_end = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int layout_constraintGuide_percent = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int layout_constraintHeight_default = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int layout_constraintHeight_max = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int layout_constraintHeight_min = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int layout_constraintHeight_percent = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int layout_constraintHorizontal_bias = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int layout_constraintHorizontal_chainStyle = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int layout_constraintHorizontal_weight = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int layout_constraintLeft_creator = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int layout_constraintLeft_toLeftOf = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int layout_constraintLeft_toRightOf = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int layout_constraintRight_creator = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int layout_constraintRight_toLeftOf = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int layout_constraintRight_toRightOf = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int layout_constraintStart_toEndOf = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int layout_constraintStart_toStartOf = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int layout_constraintTop_creator = 2130772006;
			
			// aapt resource value: 0x7f010027
			public const int layout_constraintTop_toBottomOf = 2130772007;
			
			// aapt resource value: 0x7f010028
			public const int layout_constraintTop_toTopOf = 2130772008;
			
			// aapt resource value: 0x7f010029
			public const int layout_constraintVertical_bias = 2130772009;
			
			// aapt resource value: 0x7f01002a
			public const int layout_constraintVertical_chainStyle = 2130772010;
			
			// aapt resource value: 0x7f01002b
			public const int layout_constraintVertical_weight = 2130772011;
			
			// aapt resource value: 0x7f01002c
			public const int layout_constraintWidth_default = 2130772012;
			
			// aapt resource value: 0x7f01002d
			public const int layout_constraintWidth_max = 2130772013;
			
			// aapt resource value: 0x7f01002e
			public const int layout_constraintWidth_min = 2130772014;
			
			// aapt resource value: 0x7f01002f
			public const int layout_constraintWidth_percent = 2130772015;
			
			// aapt resource value: 0x7f010030
			public const int layout_editor_absoluteX = 2130772016;
			
			// aapt resource value: 0x7f010031
			public const int layout_editor_absoluteY = 2130772017;
			
			// aapt resource value: 0x7f010032
			public const int layout_goneMarginBottom = 2130772018;
			
			// aapt resource value: 0x7f010033
			public const int layout_goneMarginEnd = 2130772019;
			
			// aapt resource value: 0x7f010034
			public const int layout_goneMarginLeft = 2130772020;
			
			// aapt resource value: 0x7f010035
			public const int layout_goneMarginRight = 2130772021;
			
			// aapt resource value: 0x7f010036
			public const int layout_goneMarginStart = 2130772022;
			
			// aapt resource value: 0x7f010037
			public const int layout_goneMarginTop = 2130772023;
			
			// aapt resource value: 0x7f010038
			public const int layout_optimizationLevel = 2130772024;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int aTelloLogo2 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int land = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int land_white = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int photogallery = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int settings_gear = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int takeoff = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int takeoff_hand = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int takeoff_white = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int takeoff_white2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int takepicture = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060029
			public const int attAngleText = 2131099689;
			
			// aapt resource value: 0x7f06000e
			public const int barrier = 2131099662;
			
			// aapt resource value: 0x7f060022
			public const int batTextView = 2131099682;
			
			// aapt resource value: 0x7f060000
			public const int bottom = 2131099648;
			
			// aapt resource value: 0x7f06000f
			public const int chains = 2131099663;
			
			// aapt resource value: 0x7f060018
			public const int connectButton = 2131099672;
			
			// aapt resource value: 0x7f060010
			public const int dimensions = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int direct = 2131099665;
			
			// aapt resource value: 0x7f06002a
			public const int eisText = 2131099690;
			
			// aapt resource value: 0x7f060001
			public const int end = 2131099649;
			
			// aapt resource value: 0x7f060028
			public const int exposureText = 2131099688;
			
			// aapt resource value: 0x7f06001b
			public const int galleryButton = 2131099675;
			
			// aapt resource value: 0x7f060006
			public const int gone = 2131099654;
			
			// aapt resource value: 0x7f06001f
			public const int hSpeedTextView = 2131099679;
			
			// aapt resource value: 0x7f060021
			public const int heiTextView = 2131099681;
			
			// aapt resource value: 0x7f060007
			public const int invisible = 2131099655;
			
			// aapt resource value: 0x7f060016
			public const int joystickViewL = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int joystickViewR = 2131099671;
			
			// aapt resource value: 0x7f060024
			public const int joystick_state = 2131099684;
			
			// aapt resource value: 0x7f060002
			public const int left = 2131099650;
			
			// aapt resource value: 0x7f06001d
			public const int linearLayout1 = 2131099677;
			
			// aapt resource value: 0x7f060019
			public const int linearLayout2 = 2131099673;
			
			// aapt resource value: 0x7f060027
			public const int maxHeightText = 2131099687;
			
			// aapt resource value: 0x7f06001e
			public const int modeTextView = 2131099678;
			
			// aapt resource value: 0x7f060012
			public const int none = 2131099666;
			
			// aapt resource value: 0x7f06000c
			public const int packed = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int parent = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int percent = 2131099657;
			
			// aapt resource value: 0x7f06001a
			public const int pictureButton = 2131099674;
			
			// aapt resource value: 0x7f060014
			public const int relativeLayout1 = 2131099668;
			
			// aapt resource value: 0x7f060003
			public const int right = 2131099651;
			
			// aapt resource value: 0x7f060025
			public const int settingsButton = 2131099685;
			
			// aapt resource value: 0x7f06000a
			public const int spread = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int spread_inside = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int standard = 2131099667;
			
			// aapt resource value: 0x7f060004
			public const int start = 2131099652;
			
			// aapt resource value: 0x7f060015
			public const int surfaceView = 2131099669;
			
			// aapt resource value: 0x7f06001c
			public const int takeoffButton = 2131099676;
			
			// aapt resource value: 0x7f060026
			public const int textView1 = 2131099686;
			
			// aapt resource value: 0x7f060005
			public const int top = 2131099653;
			
			// aapt resource value: 0x7f060020
			public const int vSpeedTextView = 2131099680;
			
			// aapt resource value: 0x7f060023
			public const int wifiTextView = 2131099683;
			
			// aapt resource value: 0x7f06000b
			public const int wrap = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Settings = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Test = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int connect_status = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int statusArea = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int statusArea2 = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ConstraintLayout_Layout = new int[] {
					16842948,
					16843039,
					16843040,
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024};
			
			// aapt resource value: 2
			public const int ConstraintLayout_Layout_android_maxHeight = 2;
			
			// aapt resource value: 1
			public const int ConstraintLayout_Layout_android_maxWidth = 1;
			
			// aapt resource value: 4
			public const int ConstraintLayout_Layout_android_minHeight = 4;
			
			// aapt resource value: 3
			public const int ConstraintLayout_Layout_android_minWidth = 3;
			
			// aapt resource value: 0
			public const int ConstraintLayout_Layout_android_orientation = 0;
			
			// aapt resource value: 5
			public const int ConstraintLayout_Layout_barrierAllowsGoneWidgets = 5;
			
			// aapt resource value: 6
			public const int ConstraintLayout_Layout_barrierDirection = 6;
			
			// aapt resource value: 7
			public const int ConstraintLayout_Layout_chainUseRtl = 7;
			
			// aapt resource value: 8
			public const int ConstraintLayout_Layout_constraintSet = 8;
			
			// aapt resource value: 9
			public const int ConstraintLayout_Layout_constraint_referenced_ids = 9;
			
			// aapt resource value: 10
			public const int ConstraintLayout_Layout_layout_constrainedHeight = 10;
			
			// aapt resource value: 11
			public const int ConstraintLayout_Layout_layout_constrainedWidth = 11;
			
			// aapt resource value: 12
			public const int ConstraintLayout_Layout_layout_constraintBaseline_creator = 12;
			
			// aapt resource value: 13
			public const int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 13;
			
			// aapt resource value: 14
			public const int ConstraintLayout_Layout_layout_constraintBottom_creator = 14;
			
			// aapt resource value: 15
			public const int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 15;
			
			// aapt resource value: 16
			public const int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 16;
			
			// aapt resource value: 17
			public const int ConstraintLayout_Layout_layout_constraintCircle = 17;
			
			// aapt resource value: 18
			public const int ConstraintLayout_Layout_layout_constraintCircleAngle = 18;
			
			// aapt resource value: 19
			public const int ConstraintLayout_Layout_layout_constraintCircleRadius = 19;
			
			// aapt resource value: 20
			public const int ConstraintLayout_Layout_layout_constraintDimensionRatio = 20;
			
			// aapt resource value: 21
			public const int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 21;
			
			// aapt resource value: 22
			public const int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 22;
			
			// aapt resource value: 23
			public const int ConstraintLayout_Layout_layout_constraintGuide_begin = 23;
			
			// aapt resource value: 24
			public const int ConstraintLayout_Layout_layout_constraintGuide_end = 24;
			
			// aapt resource value: 25
			public const int ConstraintLayout_Layout_layout_constraintGuide_percent = 25;
			
			// aapt resource value: 26
			public const int ConstraintLayout_Layout_layout_constraintHeight_default = 26;
			
			// aapt resource value: 27
			public const int ConstraintLayout_Layout_layout_constraintHeight_max = 27;
			
			// aapt resource value: 28
			public const int ConstraintLayout_Layout_layout_constraintHeight_min = 28;
			
			// aapt resource value: 29
			public const int ConstraintLayout_Layout_layout_constraintHeight_percent = 29;
			
			// aapt resource value: 30
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 30;
			
			// aapt resource value: 31
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 31;
			
			// aapt resource value: 32
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 32;
			
			// aapt resource value: 33
			public const int ConstraintLayout_Layout_layout_constraintLeft_creator = 33;
			
			// aapt resource value: 34
			public const int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 34;
			
			// aapt resource value: 35
			public const int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 35;
			
			// aapt resource value: 36
			public const int ConstraintLayout_Layout_layout_constraintRight_creator = 36;
			
			// aapt resource value: 37
			public const int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 37;
			
			// aapt resource value: 38
			public const int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 38;
			
			// aapt resource value: 39
			public const int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 39;
			
			// aapt resource value: 40
			public const int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 40;
			
			// aapt resource value: 41
			public const int ConstraintLayout_Layout_layout_constraintTop_creator = 41;
			
			// aapt resource value: 42
			public const int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 42;
			
			// aapt resource value: 43
			public const int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 43;
			
			// aapt resource value: 44
			public const int ConstraintLayout_Layout_layout_constraintVertical_bias = 44;
			
			// aapt resource value: 45
			public const int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 45;
			
			// aapt resource value: 46
			public const int ConstraintLayout_Layout_layout_constraintVertical_weight = 46;
			
			// aapt resource value: 47
			public const int ConstraintLayout_Layout_layout_constraintWidth_default = 47;
			
			// aapt resource value: 48
			public const int ConstraintLayout_Layout_layout_constraintWidth_max = 48;
			
			// aapt resource value: 49
			public const int ConstraintLayout_Layout_layout_constraintWidth_min = 49;
			
			// aapt resource value: 50
			public const int ConstraintLayout_Layout_layout_constraintWidth_percent = 50;
			
			// aapt resource value: 51
			public const int ConstraintLayout_Layout_layout_editor_absoluteX = 51;
			
			// aapt resource value: 52
			public const int ConstraintLayout_Layout_layout_editor_absoluteY = 52;
			
			// aapt resource value: 53
			public const int ConstraintLayout_Layout_layout_goneMarginBottom = 53;
			
			// aapt resource value: 54
			public const int ConstraintLayout_Layout_layout_goneMarginEnd = 54;
			
			// aapt resource value: 55
			public const int ConstraintLayout_Layout_layout_goneMarginLeft = 55;
			
			// aapt resource value: 56
			public const int ConstraintLayout_Layout_layout_goneMarginRight = 56;
			
			// aapt resource value: 57
			public const int ConstraintLayout_Layout_layout_goneMarginStart = 57;
			
			// aapt resource value: 58
			public const int ConstraintLayout_Layout_layout_goneMarginTop = 58;
			
			// aapt resource value: 59
			public const int ConstraintLayout_Layout_layout_optimizationLevel = 59;
			
			public static int[] ConstraintLayout_placeholder = new int[] {
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int ConstraintLayout_placeholder_content = 0;
			
			// aapt resource value: 1
			public const int ConstraintLayout_placeholder_emptyVisibility = 1;
			
			public static int[] ConstraintSet = new int[] {
					16842948,
					16842960,
					16842972,
					16842996,
					16842997,
					16842999,
					16843000,
					16843001,
					16843002,
					16843551,
					16843552,
					16843553,
					16843554,
					16843555,
					16843556,
					16843557,
					16843558,
					16843559,
					16843560,
					16843701,
					16843702,
					16843770,
					16843840,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023};
			
			// aapt resource value: 9
			public const int ConstraintSet_android_alpha = 9;
			
			// aapt resource value: 22
			public const int ConstraintSet_android_elevation = 22;
			
			// aapt resource value: 1
			public const int ConstraintSet_android_id = 1;
			
			// aapt resource value: 4
			public const int ConstraintSet_android_layout_height = 4;
			
			// aapt resource value: 8
			public const int ConstraintSet_android_layout_marginBottom = 8;
			
			// aapt resource value: 20
			public const int ConstraintSet_android_layout_marginEnd = 20;
			
			// aapt resource value: 5
			public const int ConstraintSet_android_layout_marginLeft = 5;
			
			// aapt resource value: 7
			public const int ConstraintSet_android_layout_marginRight = 7;
			
			// aapt resource value: 19
			public const int ConstraintSet_android_layout_marginStart = 19;
			
			// aapt resource value: 6
			public const int ConstraintSet_android_layout_marginTop = 6;
			
			// aapt resource value: 3
			public const int ConstraintSet_android_layout_width = 3;
			
			// aapt resource value: 0
			public const int ConstraintSet_android_orientation = 0;
			
			// aapt resource value: 16
			public const int ConstraintSet_android_rotation = 16;
			
			// aapt resource value: 17
			public const int ConstraintSet_android_rotationX = 17;
			
			// aapt resource value: 18
			public const int ConstraintSet_android_rotationY = 18;
			
			// aapt resource value: 14
			public const int ConstraintSet_android_scaleX = 14;
			
			// aapt resource value: 15
			public const int ConstraintSet_android_scaleY = 15;
			
			// aapt resource value: 10
			public const int ConstraintSet_android_transformPivotX = 10;
			
			// aapt resource value: 11
			public const int ConstraintSet_android_transformPivotY = 11;
			
			// aapt resource value: 12
			public const int ConstraintSet_android_translationX = 12;
			
			// aapt resource value: 13
			public const int ConstraintSet_android_translationY = 13;
			
			// aapt resource value: 21
			public const int ConstraintSet_android_translationZ = 21;
			
			// aapt resource value: 2
			public const int ConstraintSet_android_visibility = 2;
			
			// aapt resource value: 23
			public const int ConstraintSet_layout_constrainedHeight = 23;
			
			// aapt resource value: 24
			public const int ConstraintSet_layout_constrainedWidth = 24;
			
			// aapt resource value: 25
			public const int ConstraintSet_layout_constraintBaseline_creator = 25;
			
			// aapt resource value: 26
			public const int ConstraintSet_layout_constraintBaseline_toBaselineOf = 26;
			
			// aapt resource value: 27
			public const int ConstraintSet_layout_constraintBottom_creator = 27;
			
			// aapt resource value: 28
			public const int ConstraintSet_layout_constraintBottom_toBottomOf = 28;
			
			// aapt resource value: 29
			public const int ConstraintSet_layout_constraintBottom_toTopOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintSet_layout_constraintCircle = 30;
			
			// aapt resource value: 31
			public const int ConstraintSet_layout_constraintCircleAngle = 31;
			
			// aapt resource value: 32
			public const int ConstraintSet_layout_constraintCircleRadius = 32;
			
			// aapt resource value: 33
			public const int ConstraintSet_layout_constraintDimensionRatio = 33;
			
			// aapt resource value: 34
			public const int ConstraintSet_layout_constraintEnd_toEndOf = 34;
			
			// aapt resource value: 35
			public const int ConstraintSet_layout_constraintEnd_toStartOf = 35;
			
			// aapt resource value: 36
			public const int ConstraintSet_layout_constraintGuide_begin = 36;
			
			// aapt resource value: 37
			public const int ConstraintSet_layout_constraintGuide_end = 37;
			
			// aapt resource value: 38
			public const int ConstraintSet_layout_constraintGuide_percent = 38;
			
			// aapt resource value: 39
			public const int ConstraintSet_layout_constraintHeight_default = 39;
			
			// aapt resource value: 40
			public const int ConstraintSet_layout_constraintHeight_max = 40;
			
			// aapt resource value: 41
			public const int ConstraintSet_layout_constraintHeight_min = 41;
			
			// aapt resource value: 42
			public const int ConstraintSet_layout_constraintHeight_percent = 42;
			
			// aapt resource value: 43
			public const int ConstraintSet_layout_constraintHorizontal_bias = 43;
			
			// aapt resource value: 44
			public const int ConstraintSet_layout_constraintHorizontal_chainStyle = 44;
			
			// aapt resource value: 45
			public const int ConstraintSet_layout_constraintHorizontal_weight = 45;
			
			// aapt resource value: 46
			public const int ConstraintSet_layout_constraintLeft_creator = 46;
			
			// aapt resource value: 47
			public const int ConstraintSet_layout_constraintLeft_toLeftOf = 47;
			
			// aapt resource value: 48
			public const int ConstraintSet_layout_constraintLeft_toRightOf = 48;
			
			// aapt resource value: 49
			public const int ConstraintSet_layout_constraintRight_creator = 49;
			
			// aapt resource value: 50
			public const int ConstraintSet_layout_constraintRight_toLeftOf = 50;
			
			// aapt resource value: 51
			public const int ConstraintSet_layout_constraintRight_toRightOf = 51;
			
			// aapt resource value: 52
			public const int ConstraintSet_layout_constraintStart_toEndOf = 52;
			
			// aapt resource value: 53
			public const int ConstraintSet_layout_constraintStart_toStartOf = 53;
			
			// aapt resource value: 54
			public const int ConstraintSet_layout_constraintTop_creator = 54;
			
			// aapt resource value: 55
			public const int ConstraintSet_layout_constraintTop_toBottomOf = 55;
			
			// aapt resource value: 56
			public const int ConstraintSet_layout_constraintTop_toTopOf = 56;
			
			// aapt resource value: 57
			public const int ConstraintSet_layout_constraintVertical_bias = 57;
			
			// aapt resource value: 58
			public const int ConstraintSet_layout_constraintVertical_chainStyle = 58;
			
			// aapt resource value: 59
			public const int ConstraintSet_layout_constraintVertical_weight = 59;
			
			// aapt resource value: 60
			public const int ConstraintSet_layout_constraintWidth_default = 60;
			
			// aapt resource value: 61
			public const int ConstraintSet_layout_constraintWidth_max = 61;
			
			// aapt resource value: 62
			public const int ConstraintSet_layout_constraintWidth_min = 62;
			
			// aapt resource value: 63
			public const int ConstraintSet_layout_constraintWidth_percent = 63;
			
			// aapt resource value: 64
			public const int ConstraintSet_layout_editor_absoluteX = 64;
			
			// aapt resource value: 65
			public const int ConstraintSet_layout_editor_absoluteY = 65;
			
			// aapt resource value: 66
			public const int ConstraintSet_layout_goneMarginBottom = 66;
			
			// aapt resource value: 67
			public const int ConstraintSet_layout_goneMarginEnd = 67;
			
			// aapt resource value: 68
			public const int ConstraintSet_layout_goneMarginLeft = 68;
			
			// aapt resource value: 69
			public const int ConstraintSet_layout_goneMarginRight = 69;
			
			// aapt resource value: 70
			public const int ConstraintSet_layout_goneMarginStart = 70;
			
			// aapt resource value: 71
			public const int ConstraintSet_layout_goneMarginTop = 71;
			
			public static int[] LinearConstraintLayout = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int LinearConstraintLayout_android_orientation = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
