#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("aTello.Resource", IsApplication=true)]

namespace aTello
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int aTelloLogo2 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int land = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int land_white = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int photogallery = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int record = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int settings_gear = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int takeoff = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int takeoff_hand = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int takeoff_white = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int takeoff_white2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int takepicture = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int batTextView = 2131099664;
			
			// aapt resource value: 0x7f060024
			public const int cacheVideoSwitch = 2131099684;
			
			// aapt resource value: 0x7f060004
			public const int connectButton = 2131099652;
			
			// aapt resource value: 0x7f06001a
			public const int convertAllVideoButton = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int convertVideoButton = 2131099675;
			
			// aapt resource value: 0x7f060023
			public const int exposureSpinner = 2131099683;
			
			// aapt resource value: 0x7f060007
			public const int galleryButton = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int hSpeedTextView = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int heiTextView = 2131099663;
			
			// aapt resource value: 0x7f060026
			public const int iframeRateSpinner = 2131099686;
			
			// aapt resource value: 0x7f06001c
			public const int joyLayout = 2131099676;
			
			// aapt resource value: 0x7f06001f
			public const int joystickTypeSpinner = 2131099679;
			
			// aapt resource value: 0x7f060002
			public const int joystickViewL = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int joystickViewR = 2131099651;
			
			// aapt resource value: 0x7f060016
			public const int joystick_state = 2131099670;
			
			// aapt resource value: 0x7f060012
			public const int linearLayout1 = 2131099666;
			
			// aapt resource value: 0x7f060019
			public const int linearLayout3 = 2131099673;
			
			// aapt resource value: 0x7f060008
			public const int linearLayoutLeft = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int linearLayoutRight = 2131099653;
			
			// aapt resource value: 0x7f060028
			public const int lxSpinner = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int lySpinner = 2131099689;
			
			// aapt resource value: 0x7f06000c
			public const int modeTextView = 2131099660;
			
			// aapt resource value: 0x7f060020
			public const int onScreenJoySwitch = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int photoQualitySwitch = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int picLayout = 2131099682;
			
			// aapt resource value: 0x7f060006
			public const int pictureButton = 2131099654;
			
			// aapt resource value: 0x7f060013
			public const int recLightButton = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int recordButton = 2131099668;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06002a
			public const int rxSpinner = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int rySpinner = 2131099691;
			
			// aapt resource value: 0x7f060018
			public const int scrollView1 = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int settingsButton = 2131099671;
			
			// aapt resource value: 0x7f06001e
			public const int space1 = 2131099678;
			
			// aapt resource value: 0x7f06000b
			public const int statusLayout = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int surfaceView = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int takeoffButton = 2131099657;
			
			// aapt resource value: 0x7f060027
			public const int textView1 = 2131099687;
			
			// aapt resource value: 0x7f06001d
			public const int textView2 = 2131099677;
			
			// aapt resource value: 0x7f06000a
			public const int throwTakeoffButton = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int vSpeedTextView = 2131099662;
			
			// aapt resource value: 0x7f060025
			public const int vbrSpinner = 2131099685;
			
			// aapt resource value: 0x7f060015
			public const int vbrTextView = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int wifiTextView = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Settings = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int connect_status = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int rec000000 = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int statusArea = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int statusArea2 = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
