#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("aTello.Resource", IsApplication=true)]

namespace aTello
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int land = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int land_white = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int takeoff = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int takeoff_white = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int ac_state = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int attAngleText = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int button1 = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int connectButton = 2131099648;
			
			// aapt resource value: 0x7f06000d
			public const int eisText = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int exposureText = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int imageButton1 = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int joystick_state = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout1 = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int maxHeightText = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int relativeLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int surfaceView = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int takeoffButton = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int textView1 = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Settings = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int connect_status = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int statusArea = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int statusArea2 = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
